### ISSUE TITLE
New versions released by B-S-G

### ISSUE THREAD

**Issue by danielstreba** [amirzaidi/gcam#3]
Maybe you can merge the changes into this repo @amirzaidi 

[4pda.ru forum topic](https://4pda.ru/forum/index.php?showtopic=782469)
[Mirror for the latest apks by B-S-G](https://drive.google.com/open?id=0Bz85dWK2rjkZdEtnNzZTYzNud2s)

**Comment by Drive251** [comment]
also [V2.2](https://4pda.ru/forum/index.php?showtopic=782469&view=findpost&p=64128585)

note Google update camera to [4.4.020.163412804](https://www.apkmirror.com/apk/google-inc/camera/camera-4-4-020-163412804-release/google-camera-4-4-020-163412804-android-apk-download/#whatsnew)

**Comment by iamnotstanley** [comment]
New version: [Mod_GCam_4.4.012_MI5S_7.0H_Cam2API_Final_1.0.apk](https://4pda.ru/forum/index.php?showtopic=782469&st=4560#entry64178823)

**Comment by FreshhhHub** [comment]
4pda.ru = russian language only

mirror: 
Mod_GCam_4.4.012_MI5S_7.0H_Cam2API_Final_1.0.apk
https://www.androidfilehost.com/?fid=817550096634793513

Note: cannot  test...  install fine but doesn't open on Zuk Z2 PRO Snapdragon 820

**Comment by iamnotstanley** [comment]
[MGCB_7.0H_C2API_Min_v.1.0.apk](https://4pda.ru/forum/index.php?showtopic=782469&st=4740#entry64252148) (based on 4.4.020.163412804)
([mirror](https://drive.google.com/open?id=0Bz85dWK2rjkZNUZrei1xMGw2Yk0))

**Comment by gladiac** [comment]
@iamnotstanley I forked amirzaidis repo and merged B-S-G's v2.2. If you are still interested you can check out the changes here: https://github.com/gladiac1337/gcam

**Comment by danielstreba** [comment]
@gladiac1337 I had time yesterday and I did that too, but with the latest modded apks. That's why I closed this issue. [https://github.com/iamnotstanley/gcam](https://github.com/iamnotstanley/gcam)
